/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.RestaurantAdminWorkArea;

import Model.Menu.Menu;
import Model.WorkQueue.WorkRequest;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author puppalanagavaishnavi
 */
public class ChangeStatusPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChangeStatusPanel
     */
    JPanel panelBackWorkArea;
    WorkRequest workReq;

    public ChangeStatusPanel(JPanel panelBackWorkArea, WorkRequest worReq) {
        initComponents();
        this.panelBackWorkArea = panelBackWorkArea;
        this.workReq = worReq;
        
        txtOrderId.setEditable(false);
        txtTotalItems.setEditable(false);
        txtCurOrderStatus.setEditable(false);
        
        txtOrderId.setText(String.valueOf(this.workReq.getOrderRequest().getOrder_id()));
        txtTotalItems.setText(String.valueOf(this.workReq.getOrderRequest().getMenu().size()));
        txtCurOrderStatus.setText(this.workReq.getMessage());
    }
    
    
    public void populateTable() {
        DefaultTableModel menuTable = (DefaultTableModel) tblMenu.getModel();
        menuTable.setRowCount(0);
        for (Menu menuItem : workReq.getOrderRequest().getMenu()) {

            Object[] row = new Object[2];
            
            row[0] = menuItem;
            row[1] = menuItem.getFood_category();
            
            menuTable.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        lblBackBtn = new javax.swing.JLabel();
        lblCurrOrderMessage = new javax.swing.JLabel();
        lblOrderId = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JTextField();
        txtCurOrderStatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        btnPreparingOrder = new javax.swing.JButton();
        btnReadyToPickUp = new javax.swing.JButton();
        lblTotalItems = new javax.swing.JLabel();
        txtTotalItems = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(650, 650));
        setMinimumSize(new java.awt.Dimension(650, 650));

        lblHeading.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("Change Status Panel");

        lblBackBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblBackBtn.setForeground(new java.awt.Color(255, 0, 0));
        lblBackBtn.setText("<< Back");
        lblBackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackBtnMouseExited(evt);
            }
        });

        lblCurrOrderMessage.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblCurrOrderMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrOrderMessage.setText("Current Order Status:");

        lblOrderId.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblOrderId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderId.setText("Order Id:");

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMenu);

        btnPreparingOrder.setText("Preparing Order");
        btnPreparingOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreparingOrderActionPerformed(evt);
            }
        });

        btnReadyToPickUp.setText("Order Ready To Pick Up");
        btnReadyToPickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadyToPickUpActionPerformed(evt);
            }
        });

        lblTotalItems.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblTotalItems.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalItems.setText("Total Items:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCurrOrderMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(lblOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtOrderId)
                                    .addComponent(txtCurOrderStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTotalItems, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPreparingOrder))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(149, 149, 149)
                                        .addComponent(btnReadyToPickUp))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(txtTotalItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblBackBtn)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPreparingOrder, btnReadyToPickUp});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCurrOrderMessage, lblTotalItems});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCurOrderStatus, txtTotalItems});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblHeading)
                .addGap(18, 18, 18)
                .addComponent(lblBackBtn)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderId)
                    .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurrOrderMessage))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalItems)
                    .addComponent(txtTotalItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPreparingOrder)
                    .addComponent(btnReadyToPickUp))
                .addContainerGap(167, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreparingOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreparingOrderActionPerformed
        // TODO add your handling code here:
        workReq.setMessage("Preparing Order");
    }//GEN-LAST:event_btnPreparingOrderActionPerformed

    private void btnReadyToPickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadyToPickUpActionPerformed
        // TODO add your handling code here:
        workReq.setMessage("Ready For Pickup");
    }//GEN-LAST:event_btnReadyToPickUpActionPerformed

    private void lblBackBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackBtnMouseExited
        // TODO add your handling code here:
        lblBackBtn.setForeground(Color.red);
    }//GEN-LAST:event_lblBackBtnMouseExited

    private void lblBackBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackBtnMouseEntered
        // TODO add your handling code here:
        lblBackBtn.setForeground(Color.blue);
    }//GEN-LAST:event_lblBackBtnMouseEntered

    private void lblBackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackBtnMouseClicked
        // TODO add your handling code here:
        panelBackWorkArea.remove(this);
        ((java.awt.CardLayout) panelBackWorkArea.getLayout()).next(panelBackWorkArea);
    }//GEN-LAST:event_lblBackBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPreparingOrder;
    private javax.swing.JButton btnReadyToPickUp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackBtn;
    private javax.swing.JLabel lblCurrOrderMessage;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JLabel lblTotalItems;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField txtCurOrderStatus;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtTotalItems;
    // End of variables declaration//GEN-END:variables
}
