/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.RestaurantAdminWorkArea;

import Model.System.Ecosystem;
import java.awt.Color;
import javax.swing.JPanel;
import Model.Restaurant.Restaurant;
import UI.SystemAdminWorkArea.ManageRestaurantsJPanel;
import java.awt.CardLayout;

/**
 *
 * @author puppalanagavaishnavi
 */
public class RestaurantAdminWorkAreaJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
    Ecosystem ecosystem;
    private Restaurant restaurant;
    /**
     * Creates new form RestaurantAdminWorkAreaJPanel
     */
    public RestaurantAdminWorkAreaJPanel(JPanel userProcessContainer, Ecosystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem=ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageMenuJButton = new javax.swing.JButton();
        manageOrdersJButton = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblLoggedIn = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblLoggedOut = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(204, 204, 255));

        manageMenuJButton.setText("Manage menu");
        manageMenuJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMenuJButtonActionPerformed(evt);
            }
        });

        manageOrdersJButton.setText("Manage Orders");
        manageOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersJButtonActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Restaurant Admin Work Area");

        lblLoggedIn.setText("Logged In As:");

        txtUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblLoggedOut.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblLoggedOut.setForeground(new java.awt.Color(255, 0, 0));
        lblLoggedOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoggedOut.setText("Log Out");
        lblLoggedOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLoggedOut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblLoggedOutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblLoggedOutFocusLost(evt);
            }
        });
        lblLoggedOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoggedOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoggedOutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblLoggedIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLoggedOut, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageMenuJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageOrdersJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoggedOut)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoggedIn)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(manageOrdersJButton)
                .addGap(18, 18, 18)
                .addComponent(manageMenuJButton)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageMenuJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMenuJButtonActionPerformed
    ManageMenuJPanel manageMenuJPanel = new ManageMenuJPanel(userProcessContainer,ecosystem, restaurant);
       userProcessContainer.add("manageMenuJPanel", manageMenuJPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_manageMenuJButtonActionPerformed

    private void manageOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersJButtonActionPerformed
  ManageOrdersJPanel manageOrdersJPanel = new ManageOrdersJPanel(userProcessContainer,ecosystem, restaurant);
       userProcessContainer.add("manageOrdersJPanel", manageOrdersJPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);            
    }//GEN-LAST:event_manageOrdersJButtonActionPerformed

    private void lblLoggedOutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblLoggedOutFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLoggedOutFocusGained

    private void lblLoggedOutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblLoggedOutFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLoggedOutFocusLost

    private void lblLoggedOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoggedOutMouseEntered
        // TODO add your handling code here:
        lblLoggedOut.setForeground(Color.blue);
    }//GEN-LAST:event_lblLoggedOutMouseEntered

    private void lblLoggedOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoggedOutMouseExited
        // TODO add your handling code here:
        lblLoggedOut.setForeground(Color.red);
    }//GEN-LAST:event_lblLoggedOutMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLoggedIn;
    private javax.swing.JLabel lblLoggedOut;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton manageMenuJButton;
    private javax.swing.JButton manageOrdersJButton;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
