/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DeliveryManWorkArea;

import Model.WorkQueue.WorkQueue;
import Model.WorkQueue.WorkRequest;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author SRADDHA
 */
public class Currentorder extends javax.swing.JPanel {

    javax.swing.JPanel panelBackWorkArea;
    WorkRequest currentOrder;
    int flag;
    WorkQueue workQueue;

    public Currentorder(javax.swing.JPanel panelBackWorkArea, WorkRequest currentOrder, int flag, WorkQueue workQueue) {
        initComponents();
        this.panelBackWorkArea = panelBackWorkArea;
        this.currentOrder = currentOrder;
        this.flag = flag;
        this.workQueue = workQueue;

        txtid.setEditable(false);
        txtorders.setEditable(false);
        txtresaddress.setEditable(false);
        txttime.setEditable(false);
//        lblWarning.setVisible(false);

//        for (WorkRequest workRequest : this.workQueue.getWorkRequestList()) {
//            System.out.println(workRequest.getMessage());
//            System.out.println(workRequest.getStatus());
//        }
        System.out.println(currentOrder.getStatus().equals("positive"));
        if (currentOrder.getStatus().equals("positive")) {
            txtid.setText(String.valueOf(currentOrder.getOrderRequest().getOrder_id()));
            txtorders.setText(String.valueOf(currentOrder.getOrderRequest().getMenu().size()));
            txtresaddress.setText(currentOrder.getOrderRequest().getResDetails().getRes_street_add());
            txttime.setText(currentOrder.getRequestTime());
            txtStatus.setText(currentOrder.getMessage());
        } 

    }

    /**
     * Creates new form Current order
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblid = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        lblloorders = new javax.swing.JLabel();
        lblresaddress = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        txtorders = new javax.swing.JTextField();
        txtresaddress = new javax.swing.JTextField();
        btnresdetails = new javax.swing.JButton();
        btncusdetails = new javax.swing.JButton();
        lbldelcurorder = new javax.swing.JLabel();
        lbldelcurback = new javax.swing.JLabel();
        btnUpdateStatus = new javax.swing.JButton();
        lblStatusOrder = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        lblid.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblid.setText("Order ID");

        lbltime.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lbltime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltime.setText("Ordered Time");

        lblloorders.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblloorders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblloorders.setText("Number of orders");

        lblresaddress.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblresaddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblresaddress.setText("Restaurant Address");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimeActionPerformed(evt);
            }
        });

        btnresdetails.setBackground(new java.awt.Color(204, 255, 204));
        btnresdetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnresdetails.setText("Restaurant Details");
        btnresdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnresdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresdetailsActionPerformed(evt);
            }
        });

        btncusdetails.setBackground(new java.awt.Color(204, 255, 204));
        btncusdetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncusdetails.setText("Customer Details");
        btncusdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncusdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncusdetailsActionPerformed(evt);
            }
        });

        lbldelcurorder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbldelcurorder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldelcurorder.setText("CURRENT ORDER");

        lbldelcurback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldelcurback.setForeground(new java.awt.Color(255, 51, 51));
        lbldelcurback.setText("<<Back");
        lbldelcurback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbldelcurback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldelcurbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldelcurbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldelcurbackMouseExited(evt);
            }
        });

        btnUpdateStatus.setBackground(new java.awt.Color(204, 255, 204));
        btnUpdateStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnUpdateStatus.setText("Update Status");
        btnUpdateStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        lblStatusOrder.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblStatusOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatusOrder.setText("Status Of Order:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbldelcurorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnresdetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addComponent(btnUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252)
                        .addComponent(btncusdetails)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbldelcurback))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblid)
                                        .addGap(30, 30, 30)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblStatusOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbltime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblloorders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblresaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txttime, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                            .addComponent(txtorders)
                                            .addComponent(txtresaddress)
                                            .addComponent(txtStatus))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnUpdateStatus, btncusdetails, btnresdetails});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblid, lblloorders, lblresaddress, lbltime});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtStatus, txtid, txtorders, txtresaddress, txttime});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbldelcurorder)
                .addGap(18, 18, 18)
                .addComponent(lbldelcurback)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblid))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltime)
                    .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblloorders)
                    .addComponent(txtorders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblresaddress)
                    .addComponent(txtresaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusOrder)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnresdetails)
                    .addComponent(btncusdetails)
                    .addComponent(btnUpdateStatus))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimeActionPerformed

    private void btnresdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresdetailsActionPerformed
        // TODO add your handling code here:
        {
            RestaurantDetails resdetails = new RestaurantDetails(panelBackWorkArea, currentOrder.getOrderRequest().getResDetails());
            panelBackWorkArea.add("RestaurantDetails", resdetails);
            ((java.awt.CardLayout) panelBackWorkArea.getLayout()).next(panelBackWorkArea);

        }
    }//GEN-LAST:event_btnresdetailsActionPerformed

    private void btncusdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncusdetailsActionPerformed
        // TODO add your handling code here:
        {
            CustomerDetails cusdetails = new CustomerDetails(panelBackWorkArea, currentOrder.getOrderRequest().getCusDetails());
            panelBackWorkArea.add("CustomerDetails", cusdetails);
            ((java.awt.CardLayout) panelBackWorkArea.getLayout()).next(panelBackWorkArea);
        }
    }//GEN-LAST:event_btncusdetailsActionPerformed

    private void lbldelcurbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldelcurbackMouseClicked
        panelBackWorkArea.remove(this);
        ((java.awt.CardLayout) panelBackWorkArea.getLayout()).show(panelBackWorkArea, "DeliveryManWorkArea"); // TODO add your handling code here:
    }//GEN-LAST:event_lbldelcurbackMouseClicked

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        // TODO add your handling code here:
        ChangeStatusPanel changeStatusPanel = new ChangeStatusPanel(panelBackWorkArea, currentOrder, workQueue);
        panelBackWorkArea.add("Change Status Panel", changeStatusPanel);
        ((java.awt.CardLayout) panelBackWorkArea.getLayout()).next(panelBackWorkArea);
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void lbldelcurbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldelcurbackMouseEntered
        // TODO add your handling code here:
        lbldelcurback.setForeground(Color.blue);
    }//GEN-LAST:event_lbldelcurbackMouseEntered

    private void lbldelcurbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldelcurbackMouseExited
        // TODO add your handling code here:
        lbldelcurback.setForeground(Color.red);
    }//GEN-LAST:event_lbldelcurbackMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JButton btncusdetails;
    private javax.swing.JButton btnresdetails;
    private javax.swing.JLabel lblStatusOrder;
    private javax.swing.JLabel lbldelcurback;
    private javax.swing.JLabel lbldelcurorder;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblloorders;
    private javax.swing.JLabel lblresaddress;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtorders;
    private javax.swing.JTextField txtresaddress;
    private javax.swing.JTextField txttime;
    // End of variables declaration//GEN-END:variables
}
