/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DeliveryManWorkArea;

import javax.swing.JPanel;

/**
 *
 * @author SRADDHA
 */
public class Currentorder extends javax.swing.JPanel {
     javax.swing.JPanel panelBackWorkArea;
    public Currentorder(javax.swing.JPanel panelBackWorkArea) {
        initComponents();
        this.panelBackWorkArea = panelBackWorkArea;
    }
    /**
     * Creates new form Currentorder
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblid = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        lblloorders = new javax.swing.JLabel();
        lblresaddress = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        txtorders = new javax.swing.JTextField();
        txtresaddress = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        btnresdetails = new javax.swing.JButton();
        btncusdetails = new javax.swing.JButton();
        lbldelcurorder = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        lblid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblid.setText("Order ID");

        lbltime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltime.setText("Ordered Time");

        lblloorders.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblloorders.setText("Number of orders");

        lblresaddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblresaddress.setText("Restaurant Address");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimeActionPerformed(evt);
            }
        });

        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnback.setText("Back");

        btnresdetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnresdetails.setText("Restaurant Details");
        btnresdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresdetailsActionPerformed(evt);
            }
        });

        btncusdetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncusdetails.setText("Customer Details");
        btncusdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncusdetailsActionPerformed(evt);
            }
        });

        lbldelcurorder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbldelcurorder.setText("CURRENT ORDER");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\SRADDHA\\Downloads\\cur.png")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnback))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnresdetails)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btncusdetails))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbltime)
                                    .addComponent(lblloorders)
                                    .addComponent(lblresaddress))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtorders, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtresaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(lblid)
                                .addGap(92, 92, 92)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(lbldelcurorder)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbldelcurorder)
                .addGap(18, 18, 18)
                .addComponent(btnback)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblid)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltime)
                            .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblloorders)
                            .addComponent(txtorders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblresaddress)
                            .addComponent(txtresaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnresdetails)
                            .addComponent(btncusdetails)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(414, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimeActionPerformed

    private void btnresdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresdetailsActionPerformed
        // TODO add your handling code here:
        {
        RestaurantDetails resdetails = new RestaurantDetails(panelBackWorkArea);
        panelBackWorkArea.add("RestaurantDetails",resdetails);
        ((java.awt.CardLayout) panelBackWorkArea.getLayout()).next(panelBackWorkArea);
   
    }
    }//GEN-LAST:event_btnresdetailsActionPerformed

    private void btncusdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncusdetailsActionPerformed
        // TODO add your handling code here:
        {
        CustomerDetails cusdetails = new CustomerDetails();
        panelBackWorkArea.add("CustomerDetails",cusdetails);
        ((java.awt.CardLayout) panelBackWorkArea.getLayout()).next(panelBackWorkArea);
    }
    }//GEN-LAST:event_btncusdetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncusdetails;
    private javax.swing.JButton btnresdetails;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbldelcurorder;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblloorders;
    private javax.swing.JLabel lblresaddress;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtorders;
    private javax.swing.JTextField txtresaddress;
    private javax.swing.JTextField txttime;
    // End of variables declaration//GEN-END:variables
}
