/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DeliveryManWorkArea;

/**
 *
 * @author SRADDHA
 */
public class CustomerDetails extends javax.swing.JPanel {

    /**
     * Creates new form CustomerDetails
     */
    public CustomerDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleCustomerdet = new javax.swing.JLabel();
        lbldelcustid = new javax.swing.JLabel();
        lbldelcustname = new javax.swing.JLabel();
        lbldelcuststrtaddress = new javax.swing.JLabel();
        lbldelcustcity = new javax.swing.JLabel();
        lbldelcustpincode = new javax.swing.JLabel();
        lbldelcustnumber = new javax.swing.JLabel();
        txtdelcusid = new javax.swing.JTextField();
        txtdelcusname = new javax.swing.JTextField();
        txtdelcusstrtaddress = new javax.swing.JTextField();
        txtdelcustcity = new javax.swing.JTextField();
        txtdelcustpincode = new javax.swing.JTextField();
        txtdelcustnumber = new javax.swing.JTextField();
        lbldelcustemail = new javax.swing.JLabel();
        txtdelcustemail = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        titleCustomerdet.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleCustomerdet.setText("CUSTOMER DETAILS");

        lbldelcustid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldelcustid.setText("Customer_ID");

        lbldelcustname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldelcustname.setText("Name");

        lbldelcuststrtaddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldelcuststrtaddress.setText("Street Address");

        lbldelcustcity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldelcustcity.setText("City");

        lbldelcustpincode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldelcustpincode.setText("Pincode");

        lbldelcustnumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldelcustnumber.setText("Contact number");

        lbldelcustemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldelcustemail.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(titleCustomerdet))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbldelcuststrtaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldelcustemail)
                            .addComponent(lbldelcustnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldelcustcity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldelcustpincode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldelcustname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldelcustid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdelcustcity)
                            .addComponent(txtdelcusid)
                            .addComponent(txtdelcusname)
                            .addComponent(txtdelcusstrtaddress)
                            .addComponent(txtdelcustemail, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txtdelcustnumber)
                            .addComponent(txtdelcustpincode))))
                .addGap(471, 471, 471))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(titleCustomerdet)
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldelcustid)
                    .addComponent(txtdelcusid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldelcustname)
                    .addComponent(txtdelcusname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldelcuststrtaddress)
                    .addComponent(txtdelcusstrtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldelcustcity)
                    .addComponent(txtdelcustcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldelcustpincode)
                    .addComponent(txtdelcustpincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldelcustnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdelcustnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldelcustemail)
                    .addComponent(txtdelcustemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(208, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbldelcustcity;
    private javax.swing.JLabel lbldelcustemail;
    private javax.swing.JLabel lbldelcustid;
    private javax.swing.JLabel lbldelcustname;
    private javax.swing.JLabel lbldelcustnumber;
    private javax.swing.JLabel lbldelcustpincode;
    private javax.swing.JLabel lbldelcuststrtaddress;
    private javax.swing.JLabel titleCustomerdet;
    private javax.swing.JTextField txtdelcusid;
    private javax.swing.JTextField txtdelcusname;
    private javax.swing.JTextField txtdelcusstrtaddress;
    private javax.swing.JTextField txtdelcustcity;
    private javax.swing.JTextField txtdelcustemail;
    private javax.swing.JTextField txtdelcustnumber;
    private javax.swing.JTextField txtdelcustpincode;
    // End of variables declaration//GEN-END:variables
}
