/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.MenuWorkArea;

import Model.Customer.Customer;
import Model.Menu.Menu;
import Model.Menu.OrderMenuItem;
import Model.Order.Order;
import Model.Restaurant.Restaurant;
import UI.CustomerWorkArea.OrderSummaryPanel;
import java.awt.Color;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import java.util.Random;

/**
 *
 * @author amretasrerengarajan
 */
public class ViewMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewMenuPanel
     */
    javax.swing.JPanel panelBackWorkArea;
    Restaurant selectedRes;
    ArrayList<Menu> selectedMenu;
    Order order;
    int menuItemCount = 0;
    Customer cusAccount;
    java.util.Date date = new java.util.Date();
    Random rand;
    long order_id;
//    List<String> list = new ArrayList<String>();

    public ViewMenuPanel(javax.swing.JPanel panelBackWorkArea, Restaurant selectedRes, Customer cusAccount) {
        initComponents();
        selectedMenu = new ArrayList<Menu>();
        this.panelBackWorkArea = panelBackWorkArea;
        this.selectedRes = selectedRes;
        this.cusAccount = cusAccount;
        txtResName.setEditable(false);
        txtResName.setText(selectedRes.getRestaurantName());
        txtTotalItems.setEditable(false);
        rand = new Random();
        populateTable(this.selectedRes);
        order = new Order();
        order_id = rand.nextLong(5000);
    }

    public void populateTable(Restaurant res) {
        DefaultTableModel menuTable = (DefaultTableModel) tblMenu.getModel();
        menuTable.setRowCount(0);
        for (Menu menuItem : res.getMenulist()) {

            Object[] row = new Object[5];
            row[0] = menuItem.getFood_category();
            row[1] = menuItem;
            row[2] = menuItem.getFood_Qty();
            row[3] = menuItem.getFood_price();
            row[4] = menuItem.getFood_preference();
            menuTable.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblResName = new javax.swing.JLabel();
        txtResName = new javax.swing.JTextField();
        btnBack = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        lblSubTitle = new javax.swing.JLabel();
        lblTotalItems = new javax.swing.JLabel();
        txtTotalItems = new javax.swing.JTextField();
        btnViewCart = new javax.swing.JLabel();
        btnAddToCart = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(675, 675));
        setMinimumSize(new java.awt.Dimension(675, 675));
        setPreferredSize(new java.awt.Dimension(675, 675));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Menu ");

        lblResName.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        lblResName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResName.setText("Selected Restaurant Name:");

        btnBack.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 0, 0));
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBack.setText("<< Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Category", "Name", "Quantity", "Price", "Preference"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMenu);

        lblSubTitle.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblSubTitle.setForeground(new java.awt.Color(204, 255, 204));
        lblSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTitle.setText("Cart Summary");

        lblTotalItems.setText("Total Items Added:");

        btnViewCart.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnViewCart.setForeground(new java.awt.Color(255, 0, 0));
        btnViewCart.setText("View Cart >>");
        btnViewCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewCartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewCartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewCartMouseExited(evt);
            }
        });

        btnAddToCart.setBackground(new java.awt.Color(204, 255, 204));
        btnAddToCart.setText("Add To Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(btnAddToCart))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(lblResName)
                                .addGap(18, 18, 18)
                                .addComponent(txtResName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 133, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(lblTotalItems)
                .addGap(18, 18, 18)
                .addComponent(txtTotalItems, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnViewCart)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResName)
                    .addComponent(txtResName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddToCart)
                .addGap(28, 28, 28)
                .addComponent(lblSubTitle)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalItems)
                    .addComponent(txtTotalItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnViewCart)
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        panelBackWorkArea.remove(this);
        ((java.awt.CardLayout) panelBackWorkArea.getLayout()).next(panelBackWorkArea);
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        btnBack.setForeground(Color.blue);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setForeground(Color.red);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnViewCartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewCartMouseEntered
        // TODO add your handling code here:
        btnBack.setForeground(Color.blue);
    }//GEN-LAST:event_btnViewCartMouseEntered

    private void btnViewCartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewCartMouseExited
        // TODO add your handling code here:
        btnBack.setForeground(Color.red);
    }//GEN-LAST:event_btnViewCartMouseExited

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        int selectedMenuInd = tblMenu.getSelectedRow();

        if (selectedMenuInd < 0) {
            JOptionPane.showMessageDialog(this, "Select an Item before adding to cart!");
        }

        DefaultTableModel menuTable = (DefaultTableModel) tblMenu.getModel();

        Menu selectedMenuItem = (Menu) menuTable.getValueAt(selectedMenuInd, 1);

//        list.add(selectedMenuItem.getFood_name());
        order.addMenu(selectedMenuItem);
        selectedMenu.add(selectedMenuItem);

        menuItemCount++;

        txtTotalItems.setText(String.valueOf(menuItemCount));
        
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnViewCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewCartMouseClicked
        // TODO add your handling code here:\
        int qty=0;
        String time = date.getHours()+ ":" + date.getMinutes() + ":" + date.getSeconds();
        String dateCreated = date.getMonth() + "/" +  date.getDate();
        float total = 0;
        order.setResDetails(selectedRes);
        order.setCusDetails(cusAccount);
        order.setDatePlaced(dateCreated);
        order.setOrderCreatedAt(time);
        order.setOrder_id(order_id);
        
//        ArrayList<OrderMenuItem> newList = new ArrayList<OrderMenuItem>();
  
        // Traverse through the first list
//        for (Menu element : selectedMenu) {
//            if (!newList.contains(element)) {
//                qty++;
//                newList.add(element.getFood_name());
//            }
//        }
        
        for(Menu item: selectedMenu) {
            total = total + item.getFood_price();
        }
        order.setTotal(total);
        
        OrderSummaryPanel orderSummary = new OrderSummaryPanel(panelBackWorkArea, order);
        panelBackWorkArea.removeAll();
        panelBackWorkArea.add("OrderSummaryPanel", orderSummary);
        ((java.awt.CardLayout) panelBackWorkArea.getLayout()).next(panelBackWorkArea);
    }//GEN-LAST:event_btnViewCartMouseClicked

    private void tblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMenuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnViewCart;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResName;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalItems;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField txtResName;
    private javax.swing.JTextField txtTotalItems;
    // End of variables declaration//GEN-END:variables
}
