/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CustomerWorkArea;

import Model.Customer.Customer;
import java.awt.Color;

/**
 *
 * @author amretasrerengarajan
 */
public class CustomerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkArea
     */
    Customer cusAccount;

    public CustomerWorkArea(Customer cusAccount) {
        initComponents();
        this.cusAccount = cusAccount;
        txtUserName.setEditable(false);
        txtUserName.setText(cusAccount.getCustName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerLandingPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnSearchRestaurants = new javax.swing.JButton();
        btnTrackOrder = new javax.swing.JButton();
        btnViewOrderHistory = new javax.swing.JButton();
        lblLoggedIn = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblSmallHeading = new javax.swing.JLabel();
        lblLoggedOut = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        CustomerLandingPanel.setBackground(new java.awt.Color(204, 204, 255));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Customer Work Area");

        btnSearchRestaurants.setBackground(new java.awt.Color(204, 255, 204));
        btnSearchRestaurants.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        btnSearchRestaurants.setText("Search Restaurants");
        btnSearchRestaurants.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnTrackOrder.setBackground(new java.awt.Color(204, 255, 204));
        btnTrackOrder.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        btnTrackOrder.setText("Track Order");
        btnTrackOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnViewOrderHistory.setBackground(new java.awt.Color(204, 255, 204));
        btnViewOrderHistory.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        btnViewOrderHistory.setText("View Order History");
        btnViewOrderHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblLoggedIn.setText("Logged In As:");

        txtUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblSmallHeading.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        lblSmallHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSmallHeading.setText("What would You Like To Do?");

        lblLoggedOut.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblLoggedOut.setForeground(new java.awt.Color(255, 0, 0));
        lblLoggedOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoggedOut.setText("Log Out");
        lblLoggedOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLoggedOut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblLoggedOutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblLoggedOutFocusLost(evt);
            }
        });
        lblLoggedOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoggedOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoggedOutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CustomerLandingPanelLayout = new javax.swing.GroupLayout(CustomerLandingPanel);
        CustomerLandingPanel.setLayout(CustomerLandingPanelLayout);
        CustomerLandingPanelLayout.setHorizontalGroup(
            CustomerLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerLandingPanelLayout.createSequentialGroup()
                .addGroup(CustomerLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerLandingPanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(CustomerLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearchRestaurants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrackOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewOrderHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSmallHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(CustomerLandingPanelLayout.createSequentialGroup()
                                .addComponent(lblLoggedIn)
                                .addGap(18, 18, 18)
                                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CustomerLandingPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CustomerLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerLandingPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblLoggedOut, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))))
                .addContainerGap())
        );

        CustomerLandingPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSearchRestaurants, btnTrackOrder, btnViewOrderHistory, lblSmallHeading});

        CustomerLandingPanelLayout.setVerticalGroup(
            CustomerLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerLandingPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLoggedOut)
                .addGap(24, 24, 24)
                .addGroup(CustomerLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoggedIn)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(lblSmallHeading)
                .addGap(50, 50, 50)
                .addComponent(btnSearchRestaurants)
                .addGap(50, 50, 50)
                .addComponent(btnTrackOrder)
                .addGap(50, 50, 50)
                .addComponent(btnViewOrderHistory)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        add(CustomerLandingPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoggedOutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblLoggedOutFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLoggedOutFocusGained

    private void lblLoggedOutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblLoggedOutFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLoggedOutFocusLost

    private void lblLoggedOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoggedOutMouseEntered
        // TODO add your handling code here:
        lblLoggedOut.setForeground(Color.blue);
    }//GEN-LAST:event_lblLoggedOutMouseEntered

    private void lblLoggedOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoggedOutMouseExited
        // TODO add your handling code here:
        lblLoggedOut.setForeground(Color.red);
    }//GEN-LAST:event_lblLoggedOutMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerLandingPanel;
    private javax.swing.JButton btnSearchRestaurants;
    private javax.swing.JButton btnTrackOrder;
    private javax.swing.JButton btnViewOrderHistory;
    private javax.swing.JLabel lblLoggedIn;
    private javax.swing.JLabel lblLoggedOut;
    private javax.swing.JLabel lblSmallHeading;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
