/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CustomerWorkArea;

import Model.Customer.Customer;
import Model.Order.OrderList;
import Model.Restaurant.Restaurant;
import Model.Restaurant.RestaurantDirectory;
import Model.WorkQueue.WorkQueue;
import UI.Restaurants.RestaurantSearchPanel;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author amretasrerengarajan
 */
public class CustomerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkArea
     */
    Customer cusAccount;
    javax.swing.JPanel panelBackWorkArea;
    javax.swing.JPanel panelLogin;
    RestaurantDirectory resList;
    OrderList orderHis;
    WorkQueue workQueue;
    
    public CustomerWorkArea(Customer cusAccount, javax.swing.JPanel panelBackWorkArea, javax.swing.JPanel panelLogin, RestaurantDirectory resList, OrderList orderHis, WorkQueue workQueue) {
        initComponents();
        this.panelBackWorkArea = panelBackWorkArea;
        this.panelLogin = panelLogin;
        this.cusAccount = cusAccount;
        this.resList = resList;
        this.orderHis = orderHis;
        this.workQueue = workQueue;
//        this.CustomerWorkAreaPanel = new CustomerWorkArea(this.cusAccount, this.panelBackWorkArea, this.panelLogin, this.resList);
        txtUserName.setEditable(false);
        txtUserName.setText(cusAccount.getCustName());
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerLandingPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnSearchRestaurants = new javax.swing.JButton();
        btnTrackOrder = new javax.swing.JButton();
        btnViewOrderHistory = new javax.swing.JButton();
        lblLoggedIn = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblSmallHeading = new javax.swing.JLabel();
        lblLoggedOut = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(675, 675));
        setLayout(new java.awt.CardLayout());

        CustomerLandingPanel.setBackground(new java.awt.Color(204, 204, 255));
        CustomerLandingPanel.setMaximumSize(new java.awt.Dimension(675, 675));
        CustomerLandingPanel.setMinimumSize(new java.awt.Dimension(675, 675));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Customer Work Area");

        btnSearchRestaurants.setBackground(new java.awt.Color(204, 255, 204));
        btnSearchRestaurants.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        btnSearchRestaurants.setText("Search Restaurants");
        btnSearchRestaurants.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchRestaurants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchRestaurantsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchRestaurantsMouseExited(evt);
            }
        });
        btnSearchRestaurants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchRestaurantsActionPerformed(evt);
            }
        });

        btnTrackOrder.setBackground(new java.awt.Color(204, 255, 204));
        btnTrackOrder.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        btnTrackOrder.setText("Track Order");
        btnTrackOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrackOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrackOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrackOrderMouseExited(evt);
            }
        });
        btnTrackOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackOrderActionPerformed(evt);
            }
        });

        btnViewOrderHistory.setBackground(new java.awt.Color(204, 255, 204));
        btnViewOrderHistory.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        btnViewOrderHistory.setText("View Order History");
        btnViewOrderHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewOrderHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewOrderHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewOrderHistoryMouseExited(evt);
            }
        });
        btnViewOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderHistoryActionPerformed(evt);
            }
        });

        lblLoggedIn.setText("Logged In As:");

        txtUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblSmallHeading.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        lblSmallHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSmallHeading.setText("What would You Like To Do?");

        lblLoggedOut.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblLoggedOut.setForeground(new java.awt.Color(255, 0, 0));
        lblLoggedOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoggedOut.setText("Log Out");
        lblLoggedOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLoggedOut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblLoggedOutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblLoggedOutFocusLost(evt);
            }
        });
        lblLoggedOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoggedOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoggedOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoggedOutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CustomerLandingPanelLayout = new javax.swing.GroupLayout(CustomerLandingPanel);
        CustomerLandingPanel.setLayout(CustomerLandingPanelLayout);
        CustomerLandingPanelLayout.setHorizontalGroup(
            CustomerLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerLandingPanelLayout.createSequentialGroup()
                .addContainerGap(536, Short.MAX_VALUE)
                .addComponent(lblLoggedOut, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(CustomerLandingPanelLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(CustomerLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchRestaurants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrackOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewOrderHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSmallHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CustomerLandingPanelLayout.createSequentialGroup()
                        .addComponent(lblLoggedIn)
                        .addGap(18, 18, 18)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        CustomerLandingPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSearchRestaurants, btnTrackOrder, btnViewOrderHistory, lblSmallHeading});

        CustomerLandingPanelLayout.setVerticalGroup(
            CustomerLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerLandingPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLoggedOut)
                .addGap(24, 24, 24)
                .addGroup(CustomerLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoggedIn)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(lblSmallHeading)
                .addGap(50, 50, 50)
                .addComponent(btnSearchRestaurants)
                .addGap(50, 50, 50)
                .addComponent(btnTrackOrder)
                .addGap(50, 50, 50)
                .addComponent(btnViewOrderHistory)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        add(CustomerLandingPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoggedOutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblLoggedOutFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLoggedOutFocusGained

    private void lblLoggedOutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblLoggedOutFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLoggedOutFocusLost

    private void lblLoggedOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoggedOutMouseEntered
        // TODO add your handling code here:
        lblLoggedOut.setForeground(Color.blue);
    }//GEN-LAST:event_lblLoggedOutMouseEntered

    private void lblLoggedOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoggedOutMouseExited
        // TODO add your handling code here:
        lblLoggedOut.setForeground(Color.red);
    }//GEN-LAST:event_lblLoggedOutMouseExited

    private void lblLoggedOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoggedOutMouseClicked
        // TODO add your handling code here:
        panelBackWorkArea.add("LoginPanel", panelLogin);
        ((java.awt.CardLayout) panelBackWorkArea.getLayout()).next(panelBackWorkArea);
    }//GEN-LAST:event_lblLoggedOutMouseClicked

    private void btnSearchRestaurantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchRestaurantsActionPerformed
        // TODO add your handling code here:
//        panelBackWorkArea.removeAll();
        RestaurantSearchPanel searchRes = new RestaurantSearchPanel(resList, panelBackWorkArea, cusAccount, workQueue);
        panelBackWorkArea.add("SearchRestrauntsPanel", searchRes);
        ((java.awt.CardLayout) panelBackWorkArea.getLayout()).next(panelBackWorkArea);
    }//GEN-LAST:event_btnSearchRestaurantsActionPerformed

    private void btnViewOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderHistoryActionPerformed
        // TODO add your handling code here:
//        panelBackWorkArea.removeAll();
        OrderHistory orderHistory = new OrderHistory(panelBackWorkArea, orderHis);
        panelBackWorkArea.add("SearchRestrauntsPanel", orderHistory);
        ((java.awt.CardLayout) panelBackWorkArea.getLayout()).next(panelBackWorkArea);
    }//GEN-LAST:event_btnViewOrderHistoryActionPerformed

    private void btnSearchRestaurantsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRestaurantsMouseEntered
        // TODO add your handling code here:
        btnSearchRestaurants.setBackground(new Color(255, 255, 204));
    }//GEN-LAST:event_btnSearchRestaurantsMouseEntered

    private void btnSearchRestaurantsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRestaurantsMouseExited
        // TODO add your handling code here:
        btnSearchRestaurants.setBackground(new Color(204, 255, 204));

    }//GEN-LAST:event_btnSearchRestaurantsMouseExited

    private void btnTrackOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrackOrderMouseEntered
        // TODO add your handling code here:
        btnTrackOrder.setBackground(new Color(255, 255, 204));
    }//GEN-LAST:event_btnTrackOrderMouseEntered

    private void btnTrackOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrackOrderMouseExited
        // TODO add your handling code here:
        btnTrackOrder.setBackground(new Color(204, 255, 204));
    }//GEN-LAST:event_btnTrackOrderMouseExited

    private void btnViewOrderHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewOrderHistoryMouseEntered
        // TODO add your handling code here:
        btnViewOrderHistory.setBackground(new Color(255, 255, 204));
    }//GEN-LAST:event_btnViewOrderHistoryMouseEntered

    private void btnViewOrderHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewOrderHistoryMouseExited
        // TODO add your handling code here:
        btnViewOrderHistory.setBackground(new Color(204, 255, 204));

    }//GEN-LAST:event_btnViewOrderHistoryMouseExited

    private void btnTrackOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackOrderActionPerformed
        // TODO add your handling code here:
        CurrentOrderPanel trackOrder = new CurrentOrderPanel(panelBackWorkArea, workQueue, cusAccount);
        panelBackWorkArea.add("Track Order", trackOrder);
        ((java.awt.CardLayout) panelBackWorkArea.getLayout()).next(panelBackWorkArea);
    }//GEN-LAST:event_btnTrackOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerLandingPanel;
    private javax.swing.JButton btnSearchRestaurants;
    private javax.swing.JButton btnTrackOrder;
    private javax.swing.JButton btnViewOrderHistory;
    private javax.swing.JLabel lblLoggedIn;
    private javax.swing.JLabel lblLoggedOut;
    private javax.swing.JLabel lblSmallHeading;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
